version: '3.8'

services:
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "8080:80"
    networks:
      - network
    depends_on:
      - producer-app1
      - producer-app2
      - producer-app3
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    networks:
      - network
    environment:
      - POSTGRES_DB=simple
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - d-base:/var/lib/postgresql/data
  consumer-app:
    build: ./consumer
    environment:
    - PORT=8084
    - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/simple
    image: consumer-app
    container_name: consumer-app
    ports:
      - "8084:8084"
    networks:
      - network
    depends_on:
      - postgres
      - kafka
      - producer-app3

  producer-app1:
    environment:
      - PORT=8081
    image: producer
    container_name: producer-app1
    ports:
      - "8081:8081"
    networks:
      - network
    depends_on:
      - kafka
  producer-app2:
    environment:
      - PORT=8082
    image: producer
    container_name: producer-app2
    ports:
      - "8082:8082"
    networks:
      - network
    depends_on:
      - kafka
      - producer-app1
  producer-app3:
    environment:
      - PORT=8083
    image: producer
    container_name: producer-app3
    ports:
      - "8083:8083"
    networks:
      - network
    depends_on:
      - kafka
      - producer-app2

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    networks:
      - network
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: kafka
    ports:
       - "9092:9092"
    networks:
      - network
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_INTERNAL://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

networks:
  network:
    driver: bridge

volumes:
  d-base: